name: Build Executables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name PyLog scr/main.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: PyLog-Windows
          path: dist/PyLog.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name PyLog scr/main.py

      - name: Upload Linux EXE
        uses: actions/upload-artifact@v4
        with:
          name: PyLog-Linux
          path: dist/PyLog

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --name PyLog scr/main.py

      - name: Upload macOS EXE
        uses: actions/upload-artifact@v4
        with:
          name: PyLog-macOS
          path: dist/PyLog
